[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "coda-kernels"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "torch",
    "nvidia-cutlass-dsl>=4.7",
    "quack-kernels==0.6.5",
    "apache-tvm-ffi",
    "torch-c-dlpack-ext",
    "einops",
    "ipdb",
]

[tool.setuptools.dynamic]
version = { attr = "coda.__version__" }

[tool.setuptools.packages.find]
include = ["coda*"]
