[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "coda-kernels"
dynamic = ["version"]
requires-python = ">=3.10"
dependencies = [
    "torch",
    "nvidia-cutlass-dsl>=4.7",
    "quack-kernels @ git+https://github.com/HanGuo97/quack.git@2d6899605f5807e8bbe9b45e9640af559b215bb3",
    "apache-tvm-ffi",
    "torch-c-dlpack-ext",
    "einops",
    "fla-core>=0.5.0",
    "ipdb",
]

[tool.setuptools.dynamic]
version = { attr = "coda.__version__" }

[tool.setuptools.packages.find]
include = ["coda*"]
